apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-dujg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-dujg
    app.kubernetes.io/part-of: test-app-fpmf
  name: test-component-dujg
  namespace: build-e2e-oaqs-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-dujg
status:
  loadBalancer: {}
